create schema BUYCHEAP;

create table OUTLETS
(
	OUTLET_ID INTEGER,
	OUTLET_NAME VARCHAR(80)
);

create table STORES
(
	STORE_ID INTEGER not null
		constraint STORES_PK
			primary key,
	STORE_NAME VARCHAR(100),
	CITY VARCHAR(50),
	AREA VARCHAR(50),
	DISTANCE_FROM_LANDMARK INTEGER,
	ZIP_CODE INTEGER,
	PHONE_NUMBER INTEGER,
	STREET_NAME VARCHAR(100),
	OUTLET_ID INTEGER,
	DISCOUNT_PERCENTAGE INTEGER,
	COUPON_CODE VARCHAR(50)
);

create table USERS
(
	USERNAME VARCHAR(50)
		unique,
	PASSWORD VARCHAR(50),
	NAME VARCHAR(100),
	CITY VARCHAR(50),
	AREA VARCHAR(50),
	ZIP_CODE INTEGER
);

create table USER_PREFERENCES
(
	USERNAME VARCHAR(50),
	RADIUS INTEGER,
	OUTLETID INTEGER
);